### ISSUE TITLE
About shiv

### ISSUE THREAD

**Issue by Lowell-liu** [buxx/rolling#17]
hello, I saw your issue on github.Your project can use shiv, I tested my own code without success.
This is my execution order.

pip install shiv
pip install -r <(pip freeze) --target dist/
shiv --site-packages dist --compressed -p venv/bin/python -o mytest.pyz -e mytest.own:main

This is my directory structure.
project目录
--dist
--mytest
----own

Is there any lack of dependency?
I hope you can help me.

**Comment by buxx** [comment]
Hello @Lowell-liu 

I stopped try to use shiv sorry :/ I completely rewrite my GUI in Rust to avoid python packaging/compile problems ...
