### ISSUE TITLE
bug: its not possible to start local server on Windows

### ISSUE THREAD

**Issue by PhilippeAccorsi** [buxx/rolling#84]
## At present

I have downloaded the zip file for windows. After unzip, I load the `rollgui.exe` and the menu appear correctly.
After that, I tried to start local server and the game crash and if I click on window, the 2 windows panel (game and debug windows) is closed directly.

If I click first on `s2.bux.fr` I can see the login page. For the moment I not try to create account on this server.

## Expected

- not crash on windows
- if something wrong, show error in debug window

## Configfuration

- OS : Windows 10 Pro (version 20H2)
- CPU : I9-9900K
- RAM : 16 Gb

**Comment by PhilippeAccorsi** [comment]
I have found that if I start the game with rollgui.bat , the debug view is not closed automatically.

Why debug view is visible by default when starting rollgui.exe ? (is it necessary in this case)

So when the game crash, I can seen that in debug view
~~~

C:\Users\{mysuer}\Downloads\Rolling_Windows_x86-64\Rolling_Windows_x86-64>rollgui.exe
Enable bug report (configurable in config.ini)
Set login engine
setup_login_engine
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "http", username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(5000), path: "/system/version", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 10061, kind: ConnectionRefused, message: "Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée." })) }', src/server/client.rs:540:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Press enter to exit
~~~

**Comment by buxx** [comment]
> Why debug view is visible by default when starting rollgui.exe ? (is it necessary in this case)

Je ne sais pas comment indiquer à windows de garder la fenêtre ouverte :(

Pour l'erreur dont tu parles, c'est parce qu'aucun serveur ne fonctionne à ce moment là sur ta machine. Il est prévu de faire disparaitre ce bouton de toute façon ... :)

**Comment by buxx** [comment]
A noter que la façon de faire disparaitre sera la suivante : lors de la compilation du client sera indiqué le serveur de jeu. Ainsi le client sera distribué par le distributeur du serveur. L'affichage du bouton local sera fait avec un paramètre.
