### ISSUE TITLE
bug: moving with up/down key not going in next line on create user view (windows)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [buxx/rolling#85]
## At present

I tried to create an acount on s2.bux.fr server and after creating my account, I tried to create my user. In top of the view I can see help information about how to move in the interface. I can see whet is the solution to move in the view but when I use up/down keys, the page scrolling but the cursor stay on the first line.

If I click on Enter key, my user is created with the value, so its not really clear of what is the way to select other line with keybord.

## Expected

Moving with up/down key, put the cursor on next/preview line.

## Configfuration

- OS : Windows 10 Pro (version 20H2)
- CPU : I9-9900K
- RAM : 16 Gb

**Comment by buxx** [comment]
> Moving with up/down key, put the cursor on next/preview line.

C'est une bonne idée. Par contre, actuellement ces touches permettent de faire défiler l'écran lorsque le contenu d'écran (comme sur une page web). La touche TAB permet de faire ce que tu demandes ? Penses-tu que cela serais suffisant (en ajoutant l'information en haut)

> I can't edit my user after validation with Enter key, so I think I have lost all point can I normaly add to my user. Or I miss something to see where I can adjust my user capabilities ?

En effet, il faudrait ajouter une boite de confirmation sur cette page. Ça irait ?

**Comment by PhilippeAccorsi** [comment]
Oui pour les 2 propositions :)

**Comment by buxx** [comment]
Information pour le tab ajouté dans 898a02db9c5d8f92cec0079b38e737a4444599e0
