### ISSUE TITLE
Moving with back button is not really clear

### ISSUE THREAD

**Issue by PhilippeAccorsi** [buxx/rolling#86]
## At present

When I'm in the zone view, I can click on menu in the left bar. But if I open event and after that i open inventory, the back button just swith between event and inventory. 
To come back on the zone view I need to click on zone button.

If i just go in event menu, clicking on back button show me the zone view.

I not really understand why sometime back button is like zone button and sometime not.

**Comment by buxx** [comment]
Ce bouton a en effet besoin d'être repensé à beaucoup d'endroit. Voir être supprimé !
