### ISSUE TITLE
ux: when starting with new user, the user is not visible (is behind left bar menu)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [buxx/rolling#87]
## At present

I start a game with my new user but I can't seen my user in the zone view. After a click with the mouse, I seen my user come from behind the left bar menu.

## Expected

Make sure user is not behind the left bar when starting new game.

**Comment by buxx** [comment]
Ah oui en effet ... Il faut que j'agrandisse la taille des marges sur les cotés !

**Comment by buxx** [comment]
fixed in next release !
