### ISSUE TITLE
something wrong in the documentation about how install on linux (debian 10 buster)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [buxx/rolling#89]
## At present

I tried to install the game on Debian 10 Buster and I look this [documentation](https://github.com/buxx/rolling#installation). When I tried the first command, the result is

~~~
sudo apt-get install git python3 python3-venv build-essential python3-dev postgresql postgresql-server-dev-9.6
~~~
~~~
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
E: Impossible de trouver le paquet postgresql-server-dev-9.6
E: Impossible de trouver de paquet correspondant à l'expression rationnelle « postgresql-server-dev-9.6 »
E: Impossible de trouver de paquet correspondant à l'expression rationnelle « postgresql-server-dev-9.6 »
~~~

## Expected

Installation is possible on Debian 10 Buster like it is visible in the documentation.

## Configuration

OS: Linux debian 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
CPU: I9-9900K
RAM: 16Go

**Comment by buxx** [comment]
En effet, il faut que je mette ça à jour :thinking: le Dockerfile ne doit plus fonctionner non plus en fait.
