### ISSUE TITLE
I try to start rolling-server but I not understand what is wrong

### ISSUE THREAD

**Issue by PhilippeAccorsi** [buxx/rolling#90]
## At present

I try to install rolling server and when I arrive at this point, an error appear `rolling-server: error: the following arguments are required: server_config_file_path`:
~~~
Start server

rolling-server --host 127.0.0.1 --port 5002 --debug ./myworldmap.txt ./myzones ./game

Where ./myworldmap.txt is previously created world map text file, ./myzones previously generated zones folder and ./game the config folder (you can use repository folder or copied and modified one).
~~~

I not really understand what is wrong. I have tried to start with path like that `rolling-server --host 127.0.0.1 --port 5002 --debug myworldmap.txt myzones/ game/`, but its the same error.

I not reallyu understand what I need to do for `and ./game the config folder (you can use repository folder or copied and modified one).`.

**Comment by buxx** [comment]
La doc n'est pas à jour, j'ai récemment ajouté un fichier de config. Je corrige ça tout de suite.
